### PR TITLE
re-add kwargs to __new__

### PR DESCRIPTION
**Pull request by matthiasdiener**
Followup of #263. This fixes a regression from 3.0.0.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Any chance you could merge this before the new release @corenting ? I think this might break existing code otherwise.

**Comment by matthiasdiener** [comment]
A gentle ping for a review @corenting - I think this is a regression from 3.0.0.

**Comment by corenting** [comment]
Thanks for the MR and sorry for the delay, I merged it

**Comment by matthiasdiener** [comment]
Thank you!

**Pull request merged**
