### PR TITLE
add set/delete/update functions

### PR DESCRIPTION
**Pull request by matthiasdiener**
Modeled after the same API in [`immutables.Map`](https://github.com/MagicStack/immutables#api), [`pyrsistent.Map`](https://github.com/tobgu/pyrsistent/#pmap), and [`frozendict`](https://github.com/Marco-Sulla/python-frozendict#api).

### CODE REVIEW

**Comment by corenting** [comment]
I see that the upstream PR that needed these changes has been superseded by another one. Is this still needed?

**Comment by matthiasdiener** [comment]
> I see that the upstream PR that needed these changes has been superseded by another one. Is this still needed?

We would like to use these functions elsewhere, so this PR would still be useful to us.

**Comment by matthiasdiener** [comment]
Due to #263 (I think), there is now an incompatibility with `dict`. Not sure this was intentional:

```
$ python
>>> dict(a=1)
{'a': 1}
>>>
>>> from immutabledict import immutabledict
>>> immutabledict(a=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: immutabledict.__new__() got an unexpected keyword argument 'a'
```

**Comment by corenting** [comment]
Thanks for the MR!

**Pull request merged**
